/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1_grupo;

import java.awt.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author rigoberto
 */
public class MenuOpciones extends javax.swing.JFrame {
public static ArrayList<Vehiculo> registrarVehiculo = new ArrayList<>();
static BufferedReader entrada = new BufferedReader (new InputStreamReader(System.in));
//FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form MenuOpciones
     */
    public MenuOpciones() {
        initComponents();
        setLocationRelativeTo(null);
//        this.setContentPane(fondo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        btnRegistraSalidaYCalculaTarifa = new javax.swing.JButton();
        lbl_MensajeBienvenida = new javax.swing.JLabel();
        btnListaDeVehiculos = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnReporteIngresosGenerados = new javax.swing.JButton();
        lblSeleccionOpcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        btnRegistraSalidaYCalculaTarifa.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistraSalidaYCalculaTarifa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistraSalidaYCalculaTarifa.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistraSalidaYCalculaTarifa.setText("Registrar Salida y calcular Tarifa");
        btnRegistraSalidaYCalculaTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistraSalidaYCalculaTarifaActionPerformed(evt);
            }
        });

        lbl_MensajeBienvenida.setBackground(new java.awt.Color(0, 0, 0));
        lbl_MensajeBienvenida.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbl_MensajeBienvenida.setForeground(java.awt.Color.black);
        lbl_MensajeBienvenida.setText("Parqueo Vehicular");
        lbl_MensajeBienvenida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnListaDeVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        btnListaDeVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaDeVehiculos.setForeground(new java.awt.Color(0, 0, 0));
        btnListaDeVehiculos.setText("Vehiculos en el parqueo");
        btnListaDeVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDeVehiculosActionPerformed(evt);
            }
        });

        btnEntrada.setBackground(new java.awt.Color(255, 255, 255));
        btnEntrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrada.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrada.setText("Registrar Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnReporteIngresosGenerados.setBackground(new java.awt.Color(255, 255, 255));
        btnReporteIngresosGenerados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteIngresosGenerados.setForeground(new java.awt.Color(0, 0, 0));
        btnReporteIngresosGenerados.setText(" Reporte de ingresos generados ");
        btnReporteIngresosGenerados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteIngresosGeneradosActionPerformed(evt);
            }
        });

        lblSeleccionOpcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSeleccionOpcion.setForeground(new java.awt.Color(0, 0, 0));
        lblSeleccionOpcion.setText("Seleccione Una Opcion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblSeleccionOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_MensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnListaDeVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReporteIngresosGenerados, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnRegistraSalidaYCalculaTarifa)))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_MensajeBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSeleccionOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistraSalidaYCalculaTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteIngresosGenerados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaDeVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteIngresosGeneradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresosGeneradosActionPerformed
        ReporteIngresos reporte = new ReporteIngresos();
        reporte.setVisible(true);
    }//GEN-LAST:event_btnReporteIngresosGeneradosActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
       // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void btnListaDeVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDeVehiculosActionPerformed
       VehiculosParqueo parqueo = new VehiculosParqueo(registrarVehiculo);
       parqueo.setVisible(true);
    }//GEN-LAST:event_btnListaDeVehiculosActionPerformed

    private void btnRegistraSalidaYCalculaTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistraSalidaYCalculaTarifaActionPerformed
     RegistroSalidayCalcularTarifa registroSalida = new RegistroSalidayCalcularTarifa();
     registroSalida.setVisible(true);
    }//GEN-LAST:event_btnRegistraSalidaYCalculaTarifaActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        RegistroEntrada registro = new RegistroEntrada();
        registro.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnListaDeVehiculos;
    private javax.swing.JButton btnRegistraSalidaYCalculaTarifa;
    private javax.swing.JButton btnReporteIngresosGenerados;
    private javax.swing.JLabel lblSeleccionOpcion;
    private javax.swing.JLabel lbl_MensajeBienvenida;
    // End of variables declaration//GEN-END:variables
}

/*class FondoPanel extends JPanel 
{
    private Image imagen;
            
    @Override
           public void paint(Graphics g) {
               
           imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg")).getImage();
           
           g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
           
//           setOpaque(false);
           
           super.paint(g);
           }
            } */