/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1_grupo;

/**
 *
 * @author kevin
 */
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class RegistroSalidayCalcularTarifa extends javax.swing.JFrame {
    /**
     * Creates new form RegistroSalidayCalcularTarifa
     */
    private DefaultTableModel modeloTabla;
    private DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
    private Vehiculo vehiculoEncontrado = null;
    private MenuOpciones menu;

    public RegistroSalidayCalcularTarifa(MenuOpciones menu) {
        initComponents();
        this.menu = menu;
        configurarTabla();
        configurarComboBox();
        setLocationRelativeTo(null);
        tblMostrarDatos.getTableHeader().setReorderingAllowed(false);
        tblMostrarDatos.getTableHeader().setResizingAllowed(false);
    }
    private void configurarComboBox() {
        // Crea modelo de comboBox de 24 items para las horas
        cmbHoraSalida.removeAllItems();
        cmbHoraSalida.addItem("Elegir");
        for (int i = 0; i < 24; i++) {
            cmbHoraSalida.addItem(String.format("%02d:00", i)); 
        }
    }
    private void configurarTabla() {
        // Crea modelo de tabla con columnas no editables
        modeloTabla = new DefaultTableModel(
            new Object[]{"Placa", "Vehiculo", "Hora Entrada"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblMostrarDatos.setModel(modeloTabla);
        
        // Ajustar ancho de columnas
        tblMostrarDatos.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblMostrarDatos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblMostrarDatos.getColumnModel().getColumn(2).setPreferredWidth(150);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        JPanePrincipal = new javax.swing.JPanel();
        btnConfirmarSalida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        lblTitulo1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbHoraSalida = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnConfirmarSalida.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmarSalida.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarSalida.setText("Confirmar salida");
        btnConfirmarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSalidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Introduzca el N° de placa:");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblMostrarDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Vehiculo", "Hora de entrada"
            }
        ));
        jScrollPane2.setViewportView(tblMostrarDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblTitulo1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitulo1.setForeground(java.awt.Color.black);
        lblTitulo1.setText("Registro de salida");

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hora Salida: ");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbHoraSalida.setBackground(new java.awt.Color(255, 255, 255));
        cmbHoraSalida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbHoraSalida.setForeground(new java.awt.Color(0, 0, 0));
        cmbHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbHoraSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanePrincipalLayout = new javax.swing.GroupLayout(JPanePrincipal);
        JPanePrincipal.setLayout(JPanePrincipalLayout);
        JPanePrincipalLayout.setHorizontalGroup(
            JPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanePrincipalLayout.createSequentialGroup()
                .addGroup(JPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanePrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanePrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanePrincipalLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnConfirmarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnRegresar))
                    .addGroup(JPanePrincipalLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(lblTitulo1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        JPanePrincipalLayout.setVerticalGroup(
            JPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarSalida)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
        String placaBuscada = txtPlaca.getText().trim().toUpperCase();

        // Validar que se haya ingresado una placa
        if (placaBuscada.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese una placa para buscar",
                "Campo vacío",
                JOptionPane.WARNING_MESSAGE);
            txtPlaca.requestFocus();
            return;
        }
        
        // Limpiar la tabla antes de buscar
        modeloTabla.setRowCount(0);
        vehiculoEncontrado = null;
        boolean encontrado = false;
        
        // Buscar el vehículo en el ArrayList
        System.out.println("Vehicuos Diponibles para salida" + MenuOpciones.registrarVehiculo.size());
        for (Vehiculo v : MenuOpciones.registrarVehiculo) {
            if (v.getPlaca().equalsIgnoreCase(placaBuscada)) {
                vehiculoEncontrado = v;
                encontrado = true;

                // Agregar el vehículo a la tabla
                Object[] fila = new Object[3];
                fila[0] = v.getPlaca();
                fila[1] = v.getMarca();
                fila[2] = v.getHoraEntrada().format(formatter);

                modeloTabla.addRow(fila);
                break;
            }
        }//fin del for each que busca vehiculo
        
        // Si no se encontró el vehículo
        if (!encontrado) {
            JOptionPane.showMessageDialog(this,
                "No se encontró ningún vehículo con la placa: " + placaBuscada + "\n" +
                "Verifique que el vehículo esté registrado en el parqueo.",
                "Vehículo no encontrado",
                JOptionPane.ERROR_MESSAGE);
        } else {
            // Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this,
                "Vehículo encontrado",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnConfirmarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSalidaActionPerformed
    if (vehiculoEncontrado == null) {JOptionPane.showMessageDialog(this,"Primero debe buscar un vehículo","Error",JOptionPane.ERROR_MESSAGE); return; }
    
    String horaSalidaSeleccionada = (String) cmbHoraSalida.getSelectedItem();
    
    if ((horaSalidaSeleccionada == null)|| horaSalidaSeleccionada.equals("Elegir")) 
    {JOptionPane.showMessageDialog(this,"Debe seleccionar una hora de salida","Campo vacío",JOptionPane.WARNING_MESSAGE); return;}
    
    try {
        // Definir y establecer hora seleccionada
        LocalTime horaSalida = LocalTime.parse(horaSalidaSeleccionada); 
        LocalDate fechaHoy = LocalDate.now();
        LocalDateTime horaSalidaFinal = LocalDateTime.of(fechaHoy, horaSalida);
        
        if (!horaSalidaFinal.isAfter(vehiculoEncontrado.getHoraEntrada())) {
           JOptionPane.showMessageDialog(this,"Ingresa una hora posterior a la hora entrada"); return;}
                
        vehiculoEncontrado.setHoraSalida(horaSalidaFinal);
        
        // Llamar metodo calcular Tarifa y eliminar objeto
        double tarifa = vehiculoEncontrado.calcularTarifa();
        
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Confirmar salida del vehículo?\n\n" +
            "Placa: " + vehiculoEncontrado.getPlaca() + "\n" +
            "Hora entrada: " + vehiculoEncontrado.getHoraEntrada().format(DateTimeFormatter.ofPattern("HH:mm")) + "\n" +
            "Hora salida: " + horaSalidaFinal.format(DateTimeFormatter.ofPattern("HH:mm")) + "\n" +
            "Tarifa a pagar: ₡" + String.format("%.2f", tarifa),
            "Confirmar Salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            MenuOpciones.historialVehiculos.add(vehiculoEncontrado);
            MenuOpciones.registrarVehiculo.remove(vehiculoEncontrado);

            JOptionPane.showMessageDialog(this,
                "Salida registrada exitosamente\n\n" +
                "Placa: " + vehiculoEncontrado.getPlaca() + "\n" +
                "Total pagado: ₡" + String.format("%.2f", tarifa),
                "Salida Exitosa",
                JOptionPane.INFORMATION_MESSAGE);

            txtPlaca.setText("");
            modeloTabla.setRowCount(0);
            vehiculoEncontrado = null;
            txtPlaca.requestFocus();
        }
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this,
            "Formato de hora inválido. Use HH:mm",
            "Error",
            JOptionPane.ERROR_MESSAGE);
  }
    }//GEN-LAST:event_btnConfirmarSalidaActionPerformed

    private void cmbHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHoraSalidaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroSalidayCalcularTarifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroSalidayCalcularTarifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroSalidayCalcularTarifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroSalidayCalcularTarifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanePrincipal;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmarSalida;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbHoraSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables










}
